spring:
  cloud:
    gateway:
      routes:
        - id: admin-route
          uri: http://localhost:8081
          predicates:
            - Path=/admin, /admin/**
          filters:
            - PrefixPath=/api/v1
